### ISSUE TITLE
Cant remove windows defender

### ISSUE THREAD

**Issue by G59Dev** [jbara2002/windows-defender-remover#65]
Title: Could not remove Windows Defender.
Message: System.Exception: Could not remove WinDefend service.

StackTrace:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at TrustedUninstaller.GUI.windows.PrepareDialog.<>c__DisplayClass1_0.<OnLoaded>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by jbara2002** [comment]
noted. a new method is working for remove that. For now, this is not affect because the service will not run after appling the script.
